version: "3"
networks:
  kafka-redis-mongo:
    driver: bridge
services:
  zookeeper-server:
    image: 'bitnami/zookeeper:latest'
    networks:
      - kafka-redis-mongo
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka-server1:
    image: 'bitnami/kafka:latest'
    networks:
      - kafka-redis-mongo
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper-server
  app:
    container_name: app
    build: .
    environment:
      - MONGO_URL=mongo
      - REDIS_URL=redis
    ports:
      - "3009:3009"
    volumes:
      - .:/usr/app
    links:
      - mongo
      - redis
  mongo:
    container_name: mongoDB
    image: mongo
    command: mongod --quiet --logpath /dev/null 
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27017"
  redis:
    container_name: redis
    image: redis
    volumes:
      - ./data:/redis/db
    ports:
      - "6378:6379"